.PHONY: clean check fix test help

help:
	@echo "Available targets:"
	@echo "  clean        - Remove all autogenerated files"
	@echo "  check        - Run all linting tools (black, flake8, mypy, isort)"
	@echo "  fix          - Auto-fix code formatting with isort and black"
	@echo "  test         - Run pytest on the tests folder"
	@echo "  coverage     - Run tests with coverage report"
	@echo "  coverage-html - Run tests with coverage and open HTML report"

clean:
	@echo "Cleaning autogenerated files..."
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
	find . -type f -name "*.pyo" -delete 2>/dev/null || true
	find . -type f -name "*.coverage" -delete 2>/dev/null || true
	rm -rf build/ dist/ .eggs/ htmlcov/ .coverage coverage.xml 2>/dev/null || true
	@echo "Clean complete!"

check:
	@echo "Running linting tools..."
	@echo "\n=== Running black ==="
	black --check .
	@echo "\n=== Running isort ==="
	isort --check-only .
	@echo "\n=== Running flake8 ==="
	flake8 .
	@echo "\n=== Running mypy ==="
	mypy src tests examples
	@echo "\n✓ All checks passed!"

fix:
	@echo "Auto-fixing code formatting..."
	@echo "\n=== Running isort ==="
	isort .
	@echo "\n=== Running black ==="
	black .
	@echo "\n✓ Code formatting complete!"

test:
	@echo "Running tests..."
	pytest tests/ -v

coverage:
	@echo "Running tests with coverage..."
	pytest tests/ -v --cov=src/lichess_board --cov-report=term-missing --cov-report=xml --cov-fail-under=100
	@echo "\n✓ Coverage report complete!"

coverage-html:
	@echo "Running tests with coverage and generating HTML report..."
	pytest tests/ -v --cov=src/lichess_board --cov-report=html --cov-report=term-missing --cov-report=xml --cov-fail-under=100
	@echo "\nOpening coverage report in browser..."
	xdg-open htmlcov/index.html 2>/dev/null || open htmlcov/index.html 2>/dev/null || echo "Please open htmlcov/index.html manually"
	@echo "\n✓ Coverage report complete!"
