.PHONY: clean check test help

help:
	@echo "Available targets:"
	@echo "  clean  - Remove all autogenerated files"
	@echo "  check  - Run all linting tools (black, flake8, mypy, isort)"
	@echo "  test   - Run pytest on the tests folder"

clean:
	@echo "Cleaning autogenerated files..."
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true
	find . -type f -name "*.pyo" -delete 2>/dev/null || true
	find . -type f -name "*.coverage" -delete 2>/dev/null || true
	rm -rf build/ dist/ .eggs/ 2>/dev/null || true
	@echo "Clean complete!"

check:
	@echo "Running linting tools..."
	@echo "\n=== Running black ==="
	black --check .
	@echo "\n=== Running isort ==="
	isort --check-only .
	@echo "\n=== Running flake8 ==="
	flake8 .
	@echo "\n=== Running mypy ==="
	mypy src tests examples
	@echo "\n✓ All checks passed!"

test:
	@echo "Running tests..."
	pytest tests/ -v
